rename from httpd2.1 to apache2
git-svn-id: svn+ssh://svn.debian.org/svn/pkg-apache/trunk/apache2@21 01b336ce-410b-0410-9a02-a0e7f243c266

diff --git a/debian/apache2-mpm-worker.postinst b/debian/apache2-mpm-worker.postinst
--- a/debian/apache2-mpm-worker.postinst
+++ b/debian/apache2-mpm-worker.postinst
@@ -8,15 +8,15 @@ fi
 #enable cgid, but only on new installs.
 if [ -z "$2" ]; then
 	a2dismod cgi >/dev/null || true
-        a2enmod cgid >/dev/null || echo "It looks like you've deleted /etc/httpd2.1/mods-available/cgid.load, so mod_cgid cannot be enabled.  To fix this, please purge and reinstall httpd2.1-common."
+        a2enmod cgid >/dev/null || echo "It looks like you've deleted /etc/apache2/mods-available/cgid.load, so mod_cgid cannot be enabled.  To fix this, please purge and reinstall apache2-common."
 fi
 
-if [ -x "/etc/init.d/httpd2.1" ]; then
-        update-rc.d httpd2.1 defaults 91 >/dev/null
+if [ -x "/etc/init.d/apache2" ]; then
+        update-rc.d apache2 defaults 91 >/dev/null
         if [ -x /usr/sbin/invoke-rc.d ]; then
-                invoke-rc.d httpd2.1 start ||true
+                invoke-rc.d apache2 start ||true
         else
-                /etc/init.d/httpd2.1 start ||true
+                /etc/init.d/apache2 start ||true
         fi
 fi
 
