Don't ship compat symlinks for ab and friends.  Use dh_install instead of various other hacks to get files installed.
git-svn-id: svn+ssh://svn.debian.org/svn/pkg-apache/trunk/apache2@207 01b336ce-410b-0410-9a02-a0e7f243c266

diff --git a/debian/mpm-postinst-threaded b/debian/mpm-postinst-threaded
--- a/debian/mpm-postinst-threaded
+++ b/debian/mpm-postinst-threaded
@@ -8,7 +8,7 @@ fi
 #enable cgid, but only on new installs.
 if [ -z "$2" ]; then
 	a2dismod cgi >/dev/null || true
-        a2enmod cgid >/dev/null || echo "It looks like you've deleted /etc/apache2/mods-available/cgid.load, so mod_cgid cannot be enabled.  To fix this, please purge and reinstall apache2-common."
+        a2enmod cgid >/dev/null || echo "It looks like you've deleted /etc/apache2/mods-available/cgid.load, so mod_cgid cannot be enabled.  To fix this, please purge and reinstall apache2.2-common."
 fi
 
 if [ -x "/etc/init.d/apache2" ]; then
